django_app/http_site/http_site/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.views.generic.base import TemplateView


urlpatterns = [
    # url(r'^$', TemplateView.as_view(template_name='base.html'), name='base'),
    # url(r'^login/$', auth_views.login, {'template_name': 'login.html'}, name='login'),
    # url(r'^logout/$', auth_views.logout, {'template_name': 'logged_out.html'}, name='logout'),
    url(r'^admin/', admin.site.urls),
    url(r'^', include('my_app.urls')),
]

django_app/http_site/my_app/urls.py
from django.conf.urls import url,include
from . import views
from .views import RespCodeChartData,TimeChartData
from django.views.generic.base import TemplateView
from django.contrib.auth import views as auth_views
from rest_framework import routers
from rest_framework.urlpatterns import format_suffix_patterns

router = routers.DefaultRouter()
#router.register(r'buttons', views.BVS)
router.register(r'pages', views.PVS)
router.register(r'addresses', views.AVS)
router.register(r'connections', views.CVS)
router.register(r'hosts', views.PHVS)
#router.register(r'batch', views.BAVS)
router.register(r'pt', views.PTVS)
router.register(r't', views.TVS)
router.register(r'u', views.UVS)
router.register(r'page_for_client/(?P<addr>[A-Za-z0-9\-\_:|^]+)', views.PageForClientView,base_name='page_for_client_view')
router.register(r'users/(?P<mac>[\w\-]+)', views.UserView,base_name='user_view')    #get only

urlpatterns = format_suffix_patterns(router.get_urls(), allowed=['json', 'html'])

urlpatterns = [
    url(r'^api/', include(router.urls)),
    url(r'^api/users/$',views.UserViewSet.as_view()),       #for put/post
    url(r'^api/buttons/$',views.BVS.as_view()),       #for put/post
    url(r'^api/batch/$',views.BAVS.as_view()),

    url(r'^$', views.main_page, name='main_page'),
    url(r'^users/$', views.users_list, name='users_list'),
    url(r'^users/$', views.users_list, name='users_list'),
    url(r'^users/(?P<pk>[0-9]+)/$', views.user_detail, name='user_detail'),
    url(r'^tests/$', views.tests_list, name='tests_list'),
    url(r'^tests/(?P<pk>[0-9]+)/$', views.test_detail,name='test_detail'),
    url(r'^pages/$', views.pages_list, name='pages_list'),
    url(r'^pages/new/$', views.page_new, name='page_new'),
    url(r'^pages/(?P<pk>[0-9]+)/$', views.page_detail, name='page_detail'),
    url(r'^pages/(?P<pk>[0-9]+)/edit/$', views.page_edit, name='page_edit'),
    url(r'^pages/(?P<page_pk>[0-9]+)/buttons/(?P<button_pk>[0-9]+)/$', views.button_detail, name='button_detail'),
    url(r'^hosts/$', views.hosts_list, name='hosts_list'),
    url(r'^hosts/(?P<pk>[0-9]+)/$', views.host_detail, name='host_detail'),
    url(r'^pages/(?P<pk>[0-9]+)/api/resp_code_chart/data/$', RespCodeChartData.as_view(),name='resp_code_data'),
    url(r'^pages/(?P<pk>[0-9]+)/api/time_chart/data/$', TimeChartData.as_view(),name='time_data'),
    url(r'^pages/search/$', views.pages_search, name='pages_search'),
]

django_app/http_site/my_app/models.py
from django.db import models
from django.utils import timezone

# Create your models here.

class User(models.Model):
    ipv4=models.CharField(max_length=15,blank=True,null=True)
    transfer_speed=models.DecimalField(max_digits=7,decimal_places=2,null=True,blank=True)       #mb/s
    mac_address=models.CharField(max_length=16,null=True,blank=True)

    def __str__(self):
        return self.mac_address+' : '+self.ipv4

    class Meta:
        db_table='Users'

class Test(models.Model):
    user=models.ForeignKey('User', related_name='test_u',null=True,blank=True)
    date=models.DateTimeField(default=timezone.now,null=True,blank=True)
    total_time=models.BigIntegerField(null=True,blank=True) #in seconds
    total_weight=models.BigIntegerField(null=True,blank=True) #in kB
    total_weight_w_pictures=models.BigIntegerField(null=True,blank=True) #in MB
    tested_pages_amount=models.BigIntegerField(null=True,blank=True)
    tested_buttons_amount=models.BigIntegerField(null=True,blank=True)
    total_pictures_amount=models.BigIntegerField(null=True,blank=True)

    class Meta:
        db_table='Tests'

class Batch(models.Model):
    page = models.ForeignKey('Page', related_name='batch_p',null=True,blank=True)
    test = models.ForeignKey('Test', related_name='batch_t',null=True,blank=True)
    levels = models.IntegerField()

    class Meta:
        db_table='Batch'

    # def __init__(self, levels, page):
    #     self.levels=levels
    #     self.page=page


class Page_Test(models.Model):
    page=models.ForeignKey('Page',related_name='page_test_p',null=True,blank=True)
    test=models.ForeignKey('Test',related_name='page_test_t',null=True,blank=True)
    # with_pictures=models.BooleanField(default=False)
    is_working=models.NullBooleanField(default=True,null=True,blank=True)
    redirection=models.ForeignKey('Page',related_name='page_test_r',null=True,blank=True)
    response_code=models.IntegerField(1000,null=True,blank=True)
    download_time=models.IntegerField(2000,null=True,blank=True)

    class Meta:
        db_table = 'Pages_Tests'

# class Force_Tests(models.Model):
#     page=models.ForeignKey('Page')
#     levels=models.IntegerField()

    # def __str__(self):
    #     return self.date


# class Server(models.Model):
#     name=models.CharField(max_length=2000)
#     ipv4=models.CharField(max_length=15)
#
#     def __str__(self):
#         return self.name
#
#     class Meta:
#         db_table='Servers'

class Page_Host(models.Model):
    domain_name=models.CharField(max_length=2000,null=True,blank=True)
    ipv4=models.CharField(max_length=15,null=True,blank=True)

    class Meta:
        db_table="Page_hosts"

    def __str__(self):
        return "a"

class Page(models.Model):
    address=models.CharField(max_length=5000,null=True,blank=True)
    weight=models.IntegerField(null=True,blank=True)   #kB
    weight_w_pictures=models.IntegerField(null=True,blank=True) #kB
    encoding=models.CharField(max_length=50,null=True,blank=True)
    cookies_present=models.NullBooleanField(default=None,null=True,blank=True)
    avg_download_time=models.DecimalField(max_digits=12,decimal_places=2,null=True,blank=True)  #ms
    force_test = models.NullBooleanField(default=False,null=True,blank=True)
    global_working_percentage=models.DecimalField(max_digits=5,decimal_places=2,null=True,blank=True)
    last_month_working_percentage=models.DecimalField(max_digits=5,decimal_places=2,null=True,blank=True)
    redirection_percentage=models.DecimalField(max_digits=5,decimal_places=2,null=True,blank=True)
    host = models.ForeignKey('Page_Host',related_name='page_h',null=True,blank=True)
    pictures_amount=models.IntegerField(null=True,blank=True)

    class Meta:
        db_table='Pages'


class Page_Connection(models.Model):
    page_1=models.ForeignKey('Page', related_name='page_connection_1',blank=True)
    page_2=models.ForeignKey('Page', related_name='page_connection_2',blank=True)

    class Meta:
        db_table='Pages_Connections'

    def __str__(self):
        return "a"


class Button(models.Model):
    page = models.ForeignKey('Page', related_name='button_p',null=True,blank=True)
    locator=models.CharField(max_length=5000)
    global_working_percentage = models.DecimalField(max_digits=5, decimal_places=2,null=True,blank=True)
    last_month_working_percentage = models.DecimalField(max_digits=5, decimal_places=2,null=True,blank=True)

    def __str__(self):
        return self.locator

    class Meta:
        db_table='Buttons'


class T_P_B(models.Model):
    button = models.ForeignKey('Button', related_name='t_p_b_b',null=True,blank=True)
    is_working=models.NullBooleanField(null=True,blank=True)
    page_test=models.ForeignKey('Page_Test',related_name='p_t_b_pt',null=True,blank=True)

    class Meta:
        db_table='T_P_B'

django_app/http_site/my_app/views.py
from django.shortcuts import render, get_object_or_404,redirect
from .models import User,Test,Page,Page_Test,Page_Connection,T_P_B,Button,Page_Host,Batch
from django.db.models import Q
from .forms import PageForm
from django.contrib.auth import authenticate, login,logout
from django.contrib.auth.decorators import login_required
from rest_framework.response import Response
from django.db.models import Max,Min
from rest_framework.authentication import SessionAuthentication, BasicAuthentication
from rest_framework.permissions import IsAuthenticated
from django.utils.decorators import method_decorator
import re
from django.db.models import Q
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from rest_framework import viewsets
from .serializers import UserSerializer,TestSerializer,PageSerializer,Page_TestSerializer,\
    Page_ConnectionSerializer,T_P_BSerializer,ButtonSerializer,Page_HostSerializer,BatchSerializer,PageAddressSerializer,\
    Page_For_ClientSerializer
from rest_framework.response import Response
from rest_framework import status
from django.http import Http404
from rest_framework.views import APIView
from rest_framework import generics
import math
import urllib

# Create your views here.
def main_page(request):
    if request.method == "POST":
        if 'username' in request.POST and 'password' in request.POST:
            username = request.POST['username']
            password = request.POST['password']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
        else:
            if request.user.is_authenticated():
                logout(request)
            return render(request, 'my_app/logged_out.html')

    return render(request, 'my_app/base.html')

@login_required
def users_list(request):
    users = User.objects.all().order_by('id')
    for u in users:
        u.how_many=u.test_u.all().count()
    return render(request, 'my_app/users_list.html', {'users':users})

@login_required
def user_detail(request,pk):
    user = get_object_or_404(User, pk=pk)
    tests= user.test_u.all().order_by('date')                                                    #Test.objects.filter(users=user.pk)
    return render(request, 'my_app/user_detail.html', {'my_user': user,'my_user_tests':tests})

@login_required
def tests_list(request):
    tests=Test.objects.all().order_by('-id')
    page_number = request.GET.get('page_number', 1)
    paginator = Paginator(tests, 15)
    try:
        tests = paginator.page(page_number)
    except PageNotAnInteger:
        tests = paginator.page(1)
    except EmptyPage:
        tests = paginator.page(paginator.num_pages)

    return render(request,'my_app/tests_list.html',{'tests':tests})

@login_required
def test_detail(request,pk):
    test = get_object_or_404(Test, pk=pk)
    time=None
    if test.total_time is not None:
        m,s=divmod(test.total_time,60)
        time='%02d:%02d'%(m, s)
    batches = Batch.objects.filter(test=pk)
    pages_tests=Page_Test.objects.filter(test=pk)
    for pt in pages_tests:
        page=pt.page
        buttons=Button.objects.filter(page=page)
        if len(buttons)>0:
            pt.t_p_b_pt=T_P_B.objects.filter(page_test=pt.pk,button__in=buttons)

    return render(request, 'my_app/test_detail.html', {'time':time,'test': test,'batches':batches,'pages_tests':pages_tests})

@login_required
def pages_list(request):
    pages = Page.objects.filter(~Q(avg_download_time=None)).order_by('address')
    page_number = request.GET.get('page_number', 1)
    paginator = Paginator(pages, 15)
    try:
        pages = paginator.page(page_number)
    except PageNotAnInteger:
        pages = paginator.page(1)
    except EmptyPage:
        pages = paginator.page(paginator.num_pages)

    return render(request,'my_app/pages_list.html',{'pages':pages})

@login_required
def page_detail(request,pk):
    page = get_object_or_404(Page, pk=pk)
    conn=Page_Connection.objects.filter(Q(page_1=pk) | Q(page_2=pk))
    links =[]
    for c in conn:
        if c.page_1 not in links:
            links.append(c.page_1)
        if c.page_2 not in links:
            links.append(c.page_2)

    buttons = Button.objects.filter(page=pk)

    pages_tests=Page_Test.objects.filter(page=pk)
    tests_quantity=len(pages_tests)

    for b in buttons:
        b.t_p_b_b = T_P_B.objects.filter(button=b.pk)

    for pt in pages_tests:
        pt.t_p_b_pt=T_P_B.objects.filter(page_test=pt)

    return render(request, 'my_app/page_detail.html', {'page':page,'links':links,'buttons':buttons,     #'is_working_percentage':is_working_percentage,
                                                       'tests_quantity':tests_quantity,                 #'redirection_percentage':redirection_percentage,
                                                       'pages_tests':pages_tests})


@login_required
def page_edit(request, pk):
    page = get_object_or_404(Page, pk=pk)
    error=None
    if request.method == "POST":
        form = PageForm(request.POST, instance=page)
        if form.is_valid():
            page = form.save(commit=False)
            page.save()
            return redirect('page_detail', pk=page.pk)
        else:
            error = 'Invalid values'
    else:
        form = PageForm(instance=page)
    return render(request, 'my_app/page_edit.html', {'form': form,'page':page,'error': error})

@login_required
def page_new(request):
    if request.method == "POST":
        form = PageForm(request.POST)
        if form.is_valid():
            page = form.save(commit=False)
            db_pages = Page.objects.filter(address=page.address)
            if not db_pages:
                page.avg_download_time=0
                page.save()
                return redirect('page_detail', pk=page.pk)
            else:
                error='This address already exists'
                return render(request, 'my_app/page_new.html', {'form': form,'error':error})
        else:
            error = 'Invalid values'
            return render(request, 'my_app/page_new.html', {'form': form,'error':error})
    else:
        form = PageForm()
        return render(request, 'my_app/page_new.html', {'form': form})

@login_required
def button_detail(request,button_pk,page_pk):
    button = get_object_or_404(Button, pk=button_pk)
    button_tests = T_P_B.objects.filter(button=button.pk)

    button_working_percentage = None

    tests_quantity=len(button_tests)
    # if tests_quantity > 0:
    #     correct = 0;
    #     for b_test in button_tests:
    #         if b_test.is_working == True:
    #             correct += 1
    #
    #     button_working_percentage = (correct * 100.0) / len(button_tests)
    #
    # button.bb = button_working_percentage

    return render(request, 'my_app/button_detail.html', {'button': button,'tests_quantity':tests_quantity})

@login_required
def hosts_list(request):
    hosts = Page_Host.objects.all()
    return render(request, 'my_app/hosts_list.html', {'hosts':hosts})

@login_required
def host_detail(request,pk):
    host = get_object_or_404(Page_Host, pk=pk)
    pages=Page.objects.filter(host=pk)
    return render(request, 'my_app/host_detail.html', {'host': host,'pages':pages})



class RespCodeChartData(APIView):
    authentication_classes = (SessionAuthentication, BasicAuthentication)
    permission_classes = (IsAuthenticated,)

    def get(self, request,pk, format=None):
        if  Page_Test.objects.filter(page=pk).count()>0:
            resp=[{'1XX': 0},{'2XX': 0},{'3XX': 0},{'4XX': 0},{'5XX': 0}]
            for i in range(1, 6):
                arg = str(i)+'XX'
                resp[i-1][arg] = Page_Test.objects.filter(page=pk, response_code__startswith=str(i)).count()
        else:
            resp=None
        return Response(resp)


class TimeChartData(APIView):
    authentication_classes = (SessionAuthentication, BasicAuthentication)
    permission_classes = (IsAuthenticated,)

    def get(self, request,pk, format=None):
        intervals=[]
        occurrences=[]
        pt_max=Page_Test.objects.filter(page=pk).aggregate(Max('download_time'))
        pt_min=Page_Test.objects.filter(page=pk).aggregate(Min('download_time'))
        quantity=Page_Test.objects.filter(page=pk).count();
        intervals_quantity=0

        if (pt_max!=None and pt_min!=None) and pt_max['download_time__max'] == pt_min['download_time__min'] or quantity == 1:
            intervals_quantity=1
        elif quantity == 2:
            intervals_quantity=2
        elif quantity >= 3 and quantity < 10:
            intervals_quantity=3
        elif quantity>=10 and quantity<50:
            intervals_quantity = 6
        else:
            intervals_quantity=10

        if(pt_max !=None and pt_min!=None and len(pt_max)>0 and len(pt_min)>0 and
                   intervals_quantity>0 and pt_max['download_time__max']!=None and pt_min['download_time__min']!=None):
            diff = pt_max['download_time__max'] - pt_min['download_time__min']
            inc = diff / intervals_quantity

            for i in range(0, intervals_quantity):
                intervals.append(pt_min['download_time__min'] + inc * i)

            intervals.append(pt_max['download_time__max'])

            if len(intervals) == 2:
                occurrences.append(Page_Test.objects.filter(page=pk, download_time=pt_max['download_time__max']).count())
            else:
                for i in range(0, intervals_quantity):
                    occurrences.append( Page_Test.objects.filter(page=pk, download_time__lt=intervals[i + 1],
                                                           download_time__gte=intervals[i]).count())

            occurrences.append(Page_Test.objects.filter(page=pk, download_time=pt_max['download_time__max']).count())
        else:
            return Response(None)

        new_intervals=[float("{0:.2f}".format(x)) for x in intervals]

django_app/http_site/my_app/templates/my_app/base.html
<!DOCTYPE html><!--Background pattern from Subtle Patterns */-->
{% load staticfiles %}
<html>
    <head>
        <title>
            {% block title %}Admin home page{% endblock %}
        </title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
        <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

        <!-- Optional theme -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

        <!-- Latest compiled and minified JavaScript -->
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
        <link href='//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
        <link href="https://fonts.googleapis.com/css?family=Bungee+Inline&amp;subset=latin-ext" rel="stylesheet">

        <style>
            .clickable-row:hover{
                cursor: pointer;
            }
            .page-header{
                font-family: 'Bungee Inline', cursive;
            }
            input#id_force_test,input#id_cookies_present{
                width:25px;
                height:25px;
            }

        </style>
    </head>
    <body>

    <nav class="navbar navbar-inverse">
      <div class="container-fluid">
          <div class="row">
            <div class="col-lg-4 col-md-6">
                <div class="navbar-header">
                    <a class="navbar-brand" href="{% url 'main_page' %}">Admin Panel</a>
                </div>
                <ul class="nav navbar-nav">
                    <li id="home_li"><a href="{% url 'main_page' %}">Home</a></li>
                    <li id="tests_li"><a href="{% url 'tests_list' %}">Tests</a></li>
                    <li id="pages_li"><a href="{% url 'pages_list' %}">Pages</a></li>
                    <li id="users_li"><a href="{% url 'users_list' %}">Users</a></li>
                    <li id="hosts_li"><a href="{% url 'hosts_list' %}">Hosts</a></li>
                </ul>
            </div>

            <div class="col-lg-3 col-md-6" style="margin-top:7px;">
                <form method="get" action="{% url 'pages_search' %}" accept-charset="utf-8">
                    <div class="input-group">
                      <input type="text" class="form-control" name='q' placeholder="Search for...">
                      <span class="input-group-btn">
                          <input class="btn btn-secondary" type="submit" value="Submit"/>

                      </span>
                    </div>
                </form>
            </div>

            <div class="col-lg-5 col-md-12">
            {%if not user.is_authenticated%}
              <form id="signin" class="navbar-form navbar-right" action="{% url 'main_page' %}" method="POST" role="form">
                  {% csrf_token %}
                    <div class="input-group">
                        <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                        <input id="username" type="text" class="form-control" name="username" value="" placeholder="Login">
                    </div>
                    <div class="input-group">
                        <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
                        <input id="password" type="password" class="form-control" name="password" value="" placeholder="Password">
                    </div>
                  <button type="submit" class="btn btn-primary" name="login"><span class="glyphicon glyphicon-log-in"></span> Login</button>
               </form>
                {% else %}
                    <form id="signout" class="navbar-form navbar-right" action="{% url 'main_page' %}" method="POST" role="form">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-primary" name="logout"><span class="glyphicon glyphicon-log-out"></span> Logout</button>
                    </form>
                {% endif %}
            </div>
      </div>
      </div>
    </nav>

    <div class="container">

    <div class="page-header">
        <h2>
            {% block page_header %}
                {% if user.is_authenticated %}
                    WELCOME {{ user.username }}!
                {% else %}
                    HOME PAGE
                {% endif %}
            {% endblock %}
        </h2>
    </div>
        {% block content %}
            <div class="jumbotron">
                {%if not user.is_authenticated%}
                    <h1>Welcome!</h1>
                    <h2>Please log in</h2>
                {% else %}
                    <h1>Admin panel</h1>
                    <p>
                        Manage your tests and inspect results.
                    </p>
                {% endif %}
            </div>
        {% endblock %}
    </div>
    <script>
        jQuery(document).ready(function($) {
            $(".clickable-row").click(function() {
                window.location = $(this).data("href");
            });
        });

        jQuery(document).ready(function($) {
            if(window.location.pathname=="/testing/")
            {
                $(".nav li").removeClass("active");
                $("#home_li").addClass("active");
            }
          });
    </script>

</body>
</html>

django_app/http_site/my_app/templates/my_app/button_detail.html
{% extends 'my_app/base.html' %}

{% block title %}Button details{% endblock %}

{% block page_header %}Button details{% endblock %}

{% block content %}

    <div class="panel panel-primary">
        <div class="panel-heading">BUTTON ID : {{ button.pk }}</div>
        <div class="panel-body">
            <div class="row">
                <div class="col-sm-2"><b>Tests quantity: </b></div>
                <div class="col-sm-6">
                    {{tests_quantity}}
                </div>
            </div>
            <br/>
            <div class="row">
                <div class="col-sm-3">
                    <b>Global correct work:</b>
                </div>
                {% if button.global_working_percentage == None %}
                    No tests done yet...
                {% else %}
                    <div class="col-sm-6">
                        <div class="progress">
                            <div class="progress-bar" role="progressbar" aria-valuenow="{{button.global_working_percentage}}" aria-valuemin="0" aria-valuemax="100" style="width:{{button.global_working_percentage}}%">
                              {{ button.global_working_percentage }}%
                            </div>
                        </div>
                    </div>
                {% endif %}
            </div><br/>

            <div class="row">
                <div class="col-sm-3">
                    <b>Last month correct work:</b>
                </div>
                {% if button.last_month_working_percentage == None %}
                    No tests done yet...
                {% else %}
                    <div class="col-sm-6">
                        <div class="progress">
                            <div class="progress-bar" role="progressbar" aria-valuenow="{{button.last_month_working_percentage}}" aria-valuemin="0" aria-valuemax="100" style="width:{{button.last_month_working_percentage}}%">
                              {{ button.last_month_working_percentage }}%
                            </div>
                        </div>
                    </div>
                {% endif %}
            </div><br/>

            <div class="row">
                <div class="col-sm-2"><b>Locator:</b></div><div class="col-sm-10">{{ button.locator }}</div>
            </div>
        </div>
    </div>

<script type="text/javascript">
 jQuery(document).ready(function($) {

    $("div.progress-bar").each(function(){
        var value=$(this).attr("aria-valuenow");

        if(value>75)
        {
            $( this ).addClass("progress-bar-success");
        }
        else if(value<75 && value >25)
        {
            $( this ).addClass("progress-bar-warning");
        }
        else if(value<25 && value >10)
        {
            $( this ).addClass("progress-bar-danger");
        }
        else
        {
            $( this ).addClass("progress-bar-danger");
            $( this ).css("color","black");
        }
    });

    });
</script>
{% endblock content %}

django_app/http_site/my_app/templates/my_app/host_detail.html
{% extends 'my_app/base.html' %}

{% block title %}Host details{% endblock %}
{% block page_header %}Host{% endblock %}

{% block content %}

    <div class="panel panel-primary">
      <div class="panel-heading">HOST ID : {{host.pk}}</div>
      <div class="panel-body">
          <!--<div class="col-sm-2"><b>IPv4:</b></div><div class="col-sm-10">{{ host.ipv4}}</div>-->
          <div class="col-sm-2"><b>Domain:</b></div><div class="col-sm-10" style="word-wrap: break-word;">{{ host.domain_name }}</div>
      </div>
    </div>

    <b>Pages: <span class="badge">{{ pages|length }}</span></b>
    <ul class="list-group">
        {% for page in pages %}
            <li class="list-group-item">
                <a href="{% url 'page_detail' pk=page.pk %}">
                    <div class="row">
                        <div class="col-sm-12" style="word-wrap: break-word;">
                            {{ page.address }}
                        </div>
                    </div>
                </a>
            </li>
        {% empty %}
            <li class="list-group-item">No pages yet ...</li>
        {% endfor %}
    </ul>

<script>
  jQuery(document).ready(function($) {
    $(".nav li").removeClass("active");
    $("#hosts_li").addClass("active");
  });
</script>
{% endblock content %}

django_app/http_site/my_app/templates/my_app/hosts_list.html
{% extends 'my_app/base.html' %}

{% block title %}Hosts list{% endblock %}
{% block page_header %}Hosts{% endblock %}

{% block content %}

    <table class="table table-hover">
      <thead class="thead-inverse">
        <tr>
          <th>ID</th>
          <!--<th>IPv4</th>-->
          <th>Domain</th>
        </tr>
      </thead>
      <tbody>
      {% for host in hosts %}
        <tr class='clickable-row' data-href="{% url 'host_detail' pk=host.id %}">
          <td> <a color="black" href="{% url 'host_detail' pk=host.pk %}">{{ host.pk }}</a></td>
          <!--<td>{{ host.ipv4}}</td>-->
          <td style="word-wrap: break-word;">{{ host.domain_name|truncatechars:100 }}</td>
        </tr>
      {% endfor %}
      </tbody>
    </table>

<script>
  jQuery(document).ready(function($) {
    $(".nav li").removeClass("active");
    $("#hosts_li").addClass("active");
  });
</script>
{% endblock content %}

django_app/http_site/my_app/templates/my_app/logged_out.html
{% extends 'my_app/base.html' %}
{% block title %}Logged out{% endblock %}
{% block page_header %}Logged out{% endblock %}

{%block content %}
    <div class="jumbotron">
        {%if not user.is_authenticated%}
            <h1>You are logged out</h1>
            <h2>Please log in to use this panel</h2>
        {% endif %}
    </div>
<script>
  jQuery(document).ready(function($) {
    $(".nav li").removeClass("active");
  });
</script>
{% endblock %}